name: Backup

on:
  workflow_dispatch: 

jobs:
  backup:
    runs-on: ubuntu-latest
    env:
      token_v2: ${{ secrets.TOKEN_V2 }}
      space_id: ${{ secrets.SPACEID }}
      file_token: ${{ secrets.FILE_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Clean Old Backup
        run: rm -r export

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Clone backup repo
        run: git clone https://github.com/nyraa/notion-backup-tools.git

      - name: Run Backup Script
        run: python notion-backup-tools/backup.py
        
      - name: Set Git Config
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email " ${{ github.actor }}@users.noreply.github.com"
        
      - name: Commit
        run: |
          current_date=$(date +"%Y-%m-%d %H:%M:%S")
          git add export
          git commit -m "Automated commit on $current_date"
          git push